-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    activation_code text NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes_candidates
(
    activation_codes_id integer NOT NULL,
    candidates_id integer NOT NULL,
    PRIMARY KEY (activation_codes_id)
);

CREATE TABLE public.activation_codes_employers
(
    activation_codes_id integer NOT NULL,
    employers_id integer NOT NULL,
    PRIMARY KEY (activation_codes_id)
);

CREATE TABLE public.candidates
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_identity character varying(11) NOT NULL,
    birth_year character varying(4) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    web_address character varying(50) NOT NULL,
    phone_number character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_activation_by_staff
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employers_id integer NOT NULL,
    staffs_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirmed_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.staffs
(
    id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(25) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_codes_candidates
    ADD FOREIGN KEY (activation_codes_id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_codes_candidates
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.activation_codes_employers
    ADD FOREIGN KEY (activation_codes_id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_codes_employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_staff
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_staff
    ADD FOREIGN KEY (staffs_id)
    REFERENCES public.staffs (id)
    NOT VALID;


ALTER TABLE public.staffs
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;